In [1]:
import numpy as np

### 1. Creation of numpy array from list

In [3]:
lst = [1,2,3]
np_lst = np.array(lst)
np_lst

array([1, 2, 3])

In [4]:
three_d_lst = [[1,2],[3,4]]
three_d_array = np.array(three_d_lst)
three_d_array

array([[1, 2],
       [3, 4]])

### 2. arange()

In [5]:
range_test=np.arange(0,5,0.5)
range_test

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

### 3. zeros an ones for vector and matrix

In [6]:
zeros_vector=np.zeros(5)
zeros_vector

array([0., 0., 0., 0., 0.])

In [9]:
zero_matrix=np.zeros((2,3))
zero_matrix

array([[0., 0., 0.],
       [0., 0., 0.]])

In [10]:
ones_vector = np.ones(6)
ones_vector

array([1., 1., 1., 1., 1., 1.])

In [11]:
ones_matrix = np.ones((2,3))
ones_matrix

array([[1., 1., 1.],
       [1., 1., 1.]])

### 4. linspace()

<u>Difference:</u> arange() gets exclusive b in <b>[a;b)</b> with a step, linspace() gets <b>[a;b]</b> and instead of a step uses num -- number of even spaced points

In [13]:
linspace_test = np.linspace(0,10, num=10)
linspace_test

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

### 5. eye()

In [14]:
eye_test = np.eye(5)
eye_test

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

### 6. Random

In [15]:
np.random.rand(6)

array([0.82885445, 0.38308667, 0.91222328, 0.21682415, 0.22474003,
       0.60739036])

In [18]:
np.random.rand(2,2)

array([[0.29267415, 0.93216839],
       [0.98406574, 0.66130236]])

In [20]:
np.random.randint(1,200)
# [1; 200) -- randomly any of this interval

66

### 7.Reshape()

In [22]:
n_arr = np.arange(0,25)
n_arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [25]:
n_arr  = n_arr.reshape((5,5))
n_arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

### 7. Diff functions of array

In [33]:
rand_arr = np.random.randint(0,100,25)
rand_arr

array([92, 10, 39, 43, 26, 45, 79, 46, 90, 17, 91,  0, 90, 60, 44, 74, 57,
       74, 27, 69, 78, 83, 86, 82, 18])

In [34]:
rand_arr.max()

92

In [35]:
rand_arr.min()

0

In [36]:
rand_arr.argmax()

0

In [39]:
n_arr.shape

(5L, 5L)

In [40]:
n_arr.dtype

dtype('int32')

### 8. Indexing of array

slice notation

In [42]:
n_arr[0][3]

3

[a:b] notation means <b>[a;b)</b> interval

In [43]:
rand_arr

array([92, 10, 39, 43, 26, 45, 79, 46, 90, 17, 91,  0, 90, 60, 44, 74, 57,
       74, 27, 69, 78, 83, 86, 82, 18])

In [44]:
rand_arr[0:4]

array([92, 10, 39, 43])

In [45]:
rand_arr[:4]

array([92, 10, 39, 43])

In [46]:
rand_arr[4:]

array([26, 45, 79, 46, 90, 17, 91,  0, 90, 60, 44, 74, 57, 74, 27, 69, 78,
       83, 86, 82, 18])

#### broadcasting

In [47]:
rand_arr[2:6]=-1
rand_arr

array([92, 10, -1, -1, -1, -1, 79, 46, 90, 17, 91,  0, 90, 60, 44, 74, 57,
       74, 27, 69, 78, 83, 86, 82, 18])

In [48]:
rand_arr[:]=0
rand_arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0])

### 9. Copy()

if you use slices of array, you use the original array, any changes refects there, otherwise you can use a copy()

In [51]:
slice= rand_arr[0:6]
slice[:] = 5
rand_arr

array([5, 5, 5, 5, 5, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0])

In [53]:
slice = rand_arr[7:11].copy()
slice[:]=3
slice


array([3, 3, 3, 3])

In [54]:
rand_arr

array([5, 5, 5, 5, 5, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0])

double bracket notation


In [55]:
arr = np.eye(5)

In [56]:
arr[1][1]

1.0

single bracket with coma notation

In [57]:
arr[1,1]

1.0

In [58]:
n_arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [59]:
n_arr[2,4]

14

### 10. Section of array

In [60]:
n_arr[0:2,0:4]

array([[0, 1, 2, 3],
       [5, 6, 7, 8]])

### 11.Smth that blows my mind!!!

In [63]:
bool_arr = n_arr>5
bool_arr

array([[False, False, False, False, False],
       [False,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

It blows my mind!

In [64]:
n_arr[bool_arr]

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22,
       23, 24])

In [66]:
arr=np.arange(1,11)
arr[arr<5]

array([1, 2, 3, 4])

Powerful, isn't it?

### 12. Numpy operations

+,-,* are <b>broadcasted</b>

In [67]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [68]:
arr+arr

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [69]:
arr*2

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [70]:
arr+100

array([101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [74]:
arr**2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [71]:
arr = arr-1
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [72]:
arr / arr

C:\Users\novikovay\AppData\Local\Continuum\anaconda2\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in divide
  """Entry point for launching an IPython kernel.


array([0, 1, 1, 1, 1, 1, 1, 1, 1, 1])

#### In Python 3 should be nan!!!

In [73]:
arr/0

C:\Users\novikovay\AppData\Local\Continuum\anaconda2\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in divide
  """Entry point for launching an IPython kernel.


array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

#### In Python 3 should be infinity!!!

### 13.np functions

#### np.sqrt(),  np.exp(), n.log(), np.max()

In [77]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [78]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [82]:
np.log(arr)

C:\Users\novikovay\AppData\Local\Continuum\anaconda2\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [79]:
np.max(arr)

9

#### trigonometric: np.sin(), np.cos()

In [80]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [81]:
np.tan(arr)

array([ 0.        ,  1.55740772, -2.18503986, -0.14254654,  1.15782128,
       -3.38051501, -0.29100619,  0.87144798, -6.79971146, -0.45231566])

#### docs.scipy.org/doc/numpy/reference/ufuncs.html

#### np.datetime64 ()

In [6]:
 np.datetime64('2017-12-25')


numpy.datetime64('2017-12-25')

In [19]:
np.datetime64('today', 'D') 

numpy.datetime64('2019-01-29')

In [8]:
np.datetime64('2019-01', 'D')

numpy.datetime64('2019-01-01')

In [9]:
np.datetime64('2019-01-29T03:30')

numpy.datetime64('2019-01-29T03:30')

In [10]:
np.array(['2007-07-13', '2006-01-13', '2010-08-13'], dtype='datetime64')


array(['2007-07-13', '2006-01-13', '2010-08-13'], dtype='datetime64[D]')

In [12]:
np.arange('2019-01', '2019-03', dtype='datetime64[D]')

array(['2019-01-01', '2019-01-02', '2019-01-03', '2019-01-04',
       '2019-01-05', '2019-01-06', '2019-01-07', '2019-01-08',
       '2019-01-09', '2019-01-10', '2019-01-11', '2019-01-12',
       '2019-01-13', '2019-01-14', '2019-01-15', '2019-01-16',
       '2019-01-17', '2019-01-18', '2019-01-19', '2019-01-20',
       '2019-01-21', '2019-01-22', '2019-01-23', '2019-01-24',
       '2019-01-25', '2019-01-26', '2019-01-27', '2019-01-28',
       '2019-01-29', '2019-01-30', '2019-01-31', '2019-02-01',
       '2019-02-02', '2019-02-03', '2019-02-04', '2019-02-05',
       '2019-02-06', '2019-02-07', '2019-02-08', '2019-02-09',
       '2019-02-10', '2019-02-11', '2019-02-12', '2019-02-13',
       '2019-02-14', '2019-02-15', '2019-02-16', '2019-02-17',
       '2019-02-18', '2019-02-19', '2019-02-20', '2019-02-21',
       '2019-02-22', '2019-02-23', '2019-02-24', '2019-02-25',
       '2019-02-26', '2019-02-27', '2019-02-28'], dtype='datetime64[D]')

#### np.timedelta ()

- difference between np.datetime64, i.e

In [13]:
np.datetime64('2009-01-01') - np.datetime64('2008-01-01')


numpy.timedelta64(366,'D')

In [14]:
np.datetime64('2009') + np.timedelta64(20, 'D')


numpy.datetime64('2009-01-21')

In [15]:
np.timedelta64(1,'W') / np.timedelta64(1,'D')


7.0

#### np.intersect1d(d1,d2) -- common values between two arrays

#### make array immutable

In [20]:
arr = np. arange(1,6)
arr.flags.writeable = False

#### np.bincount()

result is frequencies array where the index is the number that repeats, so result=[0,2,1] means that there are 2 "1" and 1 "2", something like [1,1,2] or [2,1,1] (the order doesn't make sense)

In [4]:
import numpy as np
x = np.array([1,1,1,2,2,2,5,25,1,1])
y = np.bincount(x)
y

array([0, 5, 3, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1], dtype=int64)

#### np.repeat()

In [7]:
np.repeat([1,2],4)

array([1, 1, 1, 1, 2, 2, 2, 2])

#### np.where()

In [2]:
arr = np.arange(3,6)

check_4 = np.where(arr == 4)


In [3]:
p = check_4 [0]

In [4]:
p

array([1], dtype=int64)