# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow and in the numpy documentation. The goal of this collection is to offer a quick reference for both old and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel free to open an issue at <https://github.com/rougier/numpy-100>

#### 1. Import the numpy package under the name `np` (★☆☆)

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [20]:
print('Version={}, config={}'.format(np.__version__,np.show_config()))

lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/novikovay/AppData/Local/Continuum/anaconda2\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/novikovay/AppData/Local/Continuum/anaconda2\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/novikovay/AppData/Local/Continuum/anaconda2\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/novikovay/AppData/Local/Continuum/anaconda2\\Library\\include']
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/novikovay/AppData/Local/Continuum/anaconda2\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/novikovay/AppData/Local/Continuum/anaconda2\\Library\\include']
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/novikovay/AppData/Local/Continuum/anaconda2\\Lib

#### 3. Create a null vector of size 10 (★☆☆)

In [16]:
arr=np.empty(10)
arr

array([0.00000000e+000, 6.41835578e-314, 5.23684367e-316, 2.96439388e-323,
       1.91503306e-313, 5.23684921e-316, 5.92878775e-323, 3.18823049e-313,
       5.23685198e-316, 8.89318163e-323])

#### 4.  How to find the memory size of any array (★☆☆)

In [23]:
# I don't know

#### 5.  How to get the documentation of the numpy add function from the command line? (★☆☆)

In [ ]:
# I don't know

#### 6.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [24]:
arr[4]=1
arr

array([0.00000000e+000, 6.41835578e-314, 5.23684367e-316, 2.96439388e-323,
       1.00000000e+000, 5.23684921e-316, 5.92878775e-323, 3.18823049e-313,
       5.23685198e-316, 8.89318163e-323])

#### 7.  Create a vector with values ranging from 10 to 49 (★☆☆)

In [25]:
np.arange(10,50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 8.  Reverse a vector (first element becomes last) (★☆☆)

In [26]:
np.arange(49,9,-1)

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

#### 9.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [29]:
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆)

In [31]:
arr=np.array([1,2,0,0,4,0])
np.argwhere(arr)

array([[0],
       [1],
       [4]], dtype=int64)

#### 11. Create a 3x3 identity matrix (★☆☆)

In [32]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [33]:
np.random.rand(3,3,3)

array([[[0.21479234, 0.40626317, 0.032049  ],
        [0.75187658, 0.7644739 , 0.73327889],
        [0.73063593, 0.68443746, 0.09594626]],

       [[0.0214213 , 0.85031875, 0.16041015],
        [0.4702469 , 0.87346379, 0.93446166],
        [0.27938999, 0.04926377, 0.89414493]],

       [[0.72661665, 0.25361729, 0.80971528],
        [0.84846237, 0.4527681 , 0.35154895],
        [0.97120991, 0.53771706, 0.31493565]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [34]:
arr=np.random.rand(10,10)

In [35]:
np.max(arr)

0.982281328714118

In [36]:
np.min(arr)

0.007622231329438511

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [37]:
vector=np.random.rand(30)

In [38]:
vector

array([0.68127607, 0.950438  , 0.13918509, 0.32348834, 0.33308878,
       0.29203364, 0.27859925, 0.12622206, 0.08345036, 0.4805546 ,
       0.05022963, 0.78537349, 0.96026276, 0.39189353, 0.35060859,
       0.30248579, 0.66575736, 0.04333461, 0.12829079, 0.52125874,
       0.56062204, 0.01954326, 0.70918627, 0.32637114, 0.2901603 ,
       0.99835241, 0.93528051, 0.57851596, 0.44670159, 0.3858904 ])

In [39]:
np.mean(vector)

0.43794851189882616

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [45]:
arr=np.zeros((6,6))
arr

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [46]:
arr[0,:]=1
arr[:,0]=1
arr[:,-1]=1
arr[-1,:]=1
arr

array([[1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1.]])

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [48]:
arr=np.ones((7,7))
arr

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

In [49]:
arr[0,:]=0
arr[:,0]=0
arr[:,-1]=0
arr[-1,:]=0
arr

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

#### 17. What is the result of the following expression? (★☆☆)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [51]:
0 * np.nan

nan

In [52]:
np.nan == np.nan

False

In [53]:
np.inf > np.nan

False

In [54]:
np.nan - np.nan

nan

In [55]:
np.nan in set([np.nan])

True

In [56]:
0.3 == 3 * 0.1

False

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [64]:
arr=np.eye(5)
for i in range(1,5):
    arr[i][i-1]=i
arr

array([[1., 0., 0., 0., 0.],
       [1., 1., 0., 0., 0.],
       [0., 2., 1., 0., 0.],
       [0., 0., 3., 1., 0.],
       [0., 0., 0., 4., 1.]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [65]:
arr = np.zeros((8,8))
arr

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [68]:
for i in range(0,8):
    for j in range(0,8):
        if (i+j)%2==1:
            arr[i][j]=1
arr

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [74]:
arr = np.arange(0, 6*7*8).reshape(6,7,8)
itemindex = np.where(arr==99)
itemindex

(array([1], dtype=int64), array([5], dtype=int64), array([3], dtype=int64))

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

Same as 19

#### 22. Normalize a 5x5 random matrix (★☆☆)

In [75]:
np.random.randn(25).reshape((5,5))

array([[-1.09326337,  0.26072454, -0.26536402,  0.43202046,  0.48080319],
       [ 2.02348171,  1.8572987 , -1.12370449,  0.69025389,  1.24599964],
       [ 2.00774149, -0.25836117,  0.7407486 , -0.84419114,  1.17580064],
       [ 0.37599349, -1.40022087, -0.72718271, -0.23944038, -1.32326467],
       [-2.33109722, -2.01158605,  1.02136819,  1.80074513, -0.42882203]])

#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [76]:
# I don't know yet

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [77]:
arr1 = np.arange(0,15).reshape(5,3)
arr1

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [78]:
arr2 = np.arange(0,6).reshape(3,2)
arr2

array([[0, 1],
       [2, 3],
       [4, 5]])

In [79]:
arr = np.dot(arr1, arr2)
arr

array([[ 10,  13],
       [ 28,  40],
       [ 46,  67],
       [ 64,  94],
       [ 82, 121]])

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [86]:
arr = np.arange(0,25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [87]:
for i in range(0, arr.size):
    if (arr[i]>3 and arr[i]<8):
        arr[i]=arr[i]*(-1)
arr
   

array([ 0,  1,  2,  3, -4, -5, -6, -7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

#### 26. What is the output of the following script? (★☆☆)

```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [89]:
sum(range(5),-1)

10

#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)

```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [94]:
Z = np.arange(0,3)
Z


array([0, 1, 2])

In [95]:
Z**Z

array([1, 1, 4])

#### 28. What are the result of the following expressions?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [4]:
np.array([np.nan]).astype(int).astype(float)

array([-2.14748365e+09])

#### 29. How to round away from zero a float array ? (★☆☆)

In [ ]:
#I don't know

#### 30. How to find common values between two arrays? (★☆☆)

In [6]:
d1 = np.arange(1,10)
d2 = np.arange(1,6)

In [8]:
np.intersect1d(d1,d2)

array([1, 2, 3, 4, 5])

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [9]:
np.seterr()

{'divide': 'warn', 'invalid': 'warn', 'over': 'warn', 'under': 'ignore'}

#### 32. Is the following expressions true? (★☆☆)

```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [10]:
np.sqrt(-1) == np.emath.sqrt(-1)

C:\Users\novikovay\AppData\Local\Continuum\anaconda2\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


False

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [17]:
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
print("Yesterday: ",yesterday)

('Yesterday: ', numpy.datetime64('2019-01-28'))


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [18]:
np.arange('2016-07-01', '2016-07-31', dtype='datetime64[D]')

array(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
       '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
       '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
       '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
       '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
       '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
       '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
       '2016-07-29', '2016-07-30'], dtype='datetime64[D]')

#### 35. How to compute ((A+B)\*(-A/2)) in place (without copy)? (★★☆)

In [19]:
#I don't know

#### 36. Extract the integer part of a random array using 5 different methods (★★☆)

In [21]:
#I don't know

#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [22]:
np.random.randint(0,5,(5,5))

array([[1, 1, 3, 0, 0],
       [2, 2, 3, 1, 2],
       [0, 0, 1, 4, 1],
       [3, 4, 1, 0, 1],
       [2, 4, 1, 0, 4]])

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [23]:
np.random.randint(0,100, (1,10))

array([[99, 75, 80, 63, 71, 99, 88, 82, 45, 63]])

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [39]:
np.linspace(0.0000000000000001, 0.999999999, num=10)

array([1.00000000e-16, 1.11111111e-01, 2.22222222e-01, 3.33333333e-01,
       4.44444444e-01, 5.55555555e-01, 6.66666666e-01, 7.77777777e-01,
       8.88888888e-01, 9.99999999e-01])

#### 40. Create a random vector of size 10 and sort it (★★☆)

In [49]:
sorted = np.random.rand(1,10)
sorted.sort()
sorted

array([[0.06859082, 0.13171454, 0.30396147, 0.3310559 , 0.42479063,
        0.68584307, 0.71964855, 0.75871744, 0.94321307, 0.98260526]])

#### 41. How to sum a small array faster than np.sum? (★★☆)

In [51]:
np_arr = np.arange(1,9)
# I don't know

#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [56]:
A = np.random.randint(1,10, (1,5))
B  = np.random.randint(1,10, (1,5))

A[A != B].any()

True

In [57]:
A = np.arange(1,5)
B  = np.arange(1,5)

A[A != B].any()

False

#### 43. Make an array immutable (read-only) (★★☆)

In [61]:
arr = np. arange(1,6)
arr.flags.writeable = False

In [64]:
arr[2] = 5

ValueError: assignment destination is read-only

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [75]:
A = np.random.randint(-10, 10, (10, 2))
A

array([[ -3,  -3],
       [  7,   4],
       [ -4,   2],
       [ -5,   7],
       [  9,   4],
       [  2,  -4],
       [ -7,   2],
       [-10,  -4],
       [  7,   1],
       [  6,   4]])

In [81]:
2**3

8

In [84]:
B = np.zeros((10,2))
B[:,0]=np.sqrt(A[:, 0]**2 + A[:,1]**2)
B[:, 1]= 1.0 * A[:, 1] / A [:, 0]
B

array([[ 4.24264069,  1.        ],
       [ 8.06225775,  0.57142857],
       [ 4.47213595, -0.5       ],
       [ 8.60232527, -1.4       ],
       [ 9.8488578 ,  0.44444444],
       [ 4.47213595, -2.        ],
       [ 7.28010989, -0.28571429],
       [10.77032961,  0.4       ],
       [ 7.07106781,  0.14285714],
       [ 7.21110255,  0.66666667]])

#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [100]:
V = np.random.randint(1,50, 10)

In [89]:
V[V.argmax()] = 0
V

array([34, 18, 35, 16, 27, 16, 17,  0, 38, 32])

#### 46. Create a structured array with `x` and `y` coordinates covering the \[0,1\]x\[0,1\] area (★★☆)

In [93]:
# I don't know

####  47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj))

In [94]:
# I don't know

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

In [101]:
print('['+str(V.min())+','+str(V.max())+']' )

[16,49]


#### 49. How to print all the values of an array? (★★☆)

In [104]:
# I don't understand

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [106]:
V = np.random.randint(1,50, 10)
V

array([ 5, 45, 45, 33, 26, 35, 43, 17,  6,  8])

In [110]:
c = 44
Vc=np.abs(V-c)
closest = V [Vc.argmin()]
closest

45

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

In [111]:
# To study a structured array

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

In [183]:
vector = np.random.random()


In [184]:
vector

0.7120608745236301

In [174]:
euclid_distance = np.zeros(100, dtype = float)
euclid_distance= 1.0* (vector[:,0]**2 + vector[:,1]**2)



In [175]:
euclid_distance


ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [115]:
manhattan_distance=np.zeros((100,1))

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

#### 54. How to read the following file? (★★☆)

```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

#### 56. Generate a generic 2D Gaussian-like array (★★☆)

#### 57. How to randomly place p elements in a 2D array? (★★☆)

#### 58. Subtract the mean of each row of a matrix (★★☆)

#### 59. How to sort an array by the nth column? (★★☆)

#### 60. How to tell if a given 2D array has null columns? (★★☆)

#### 61. Find the nearest value from a given value in an array (★★☆)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

#### 63. Create an array class that has a name attribute (★★☆)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

#### 70. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z\[0\],Z\[1\],Z\[2\]) and each subsequent row is  shifted by 1 (last row should be (Z\[-3\],Z\[-2\],Z\[-1\]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i  (P0\[i\],P1\[i\])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P\[j\]) to each line i (P0\[i\],P1\[i\])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = \[1,2,3,4,5,6,7,8,9,10,11,12,13,14\], how to generate an array R = \[\[1,2,3,4\], \[2,3,4,5\], \[3,4,5,6\], ..., \[11,12,13,14\]\]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z\[i,j\] == Z\[j,i\] (★★★)

#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. \[2,2,3\]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)